global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "demo-rollup"
    static_configs:
      - targets: ["host.docker.internal:9845"]

  - job_name: "hyp-relayer"
    static_configs:
      - targets: ["host.docker.internal:9091"]

  - job_name: "hyp-validator-solana"
    static_configs:
      - targets: ["host.docker.internal:9092"]

  - job_name: "hyp-validator-sovereign"
    static_configs:
      - targets: ["host.docker.internal:9093"]
